"""
Blog Writer Agent for generating entertaining blog posts
Uses Microsoft Agent Framework with Azure AI Foundry
"""
from typing import Any, Dict
import logging
from .base_agent import BaseAgent

logger = logging.getLogger(__name__)


class BlogWriterAgent(BaseAgent):
    """
    Agent specialized in writing entertaining blog posts
    from telemetry data and notifications
    """
    
    def __init__(self, name: str = "BlogWriter", model_deployment: str = "gpt-4"):
        """Initialize the Blog Writer Agent"""
        description = (
            "An AI agent specialized in creating entertaining and engaging blog posts "
            "from telemetry data and IoT notifications. You excel at turning raw data "
            "into compelling narratives that captivate readers."
        )
        super().__init__(name, description, model_deployment)
        self.writing_style = "entertaining"
    
    def get_system_prompt(self) -> str:
        """Get the specialized system prompt for blog writing"""
        return (
            f"{super().get_system_prompt()}\n\n"
            "Your role is to:\n"
            "1. Transform technical telemetry data into engaging stories\n"
            "2. Create blog posts that are both informative and entertaining\n"
            "3. Use creative narratives to explain IoT events and patterns\n"
            "4. Make technical content accessible to general audiences\n"
            "5. Include vivid descriptions and interesting insights\n\n"
            f"Write in an {self.writing_style} style that keeps readers engaged."
        )
    
    async def process(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Process telemetry data and generate blog post content
        
        Args:
            input_data: Contains message, context with telemetry data
            
        Returns:
            Dict with response containing the blog post
        """
        message = input_data.get("message", "")
        context = input_data.get("context", {})
        telemetry_data = context.get("telemetry", {})
        
        logger.info(f"[{self.name}] Processing blog post request")
        
        # In a real implementation, this would call Azure AI Foundry's model
        # For now, we'll create a structured response that demonstrates the pattern
        
        # Extract key information from telemetry
        events = telemetry_data.get("events", [])
        summary = telemetry_data.get("summary", "")
        
        # Generate blog post (this would use Azure OpenAI in production)
        blog_post = self._generate_blog_post(message, events, summary)
        
        logger.info(f"[{self.name}] Generated blog post with {len(blog_post)} characters")
        
        return {
            "response": blog_post,
            "metadata": {
                "agent": self.name,
                "word_count": len(blog_post.split()),
                "style": self.writing_style
            }
        }
    
    def _generate_blog_post(self, message: str, events: list, summary: str) -> str:
        """
        Generate blog post content
        
        Note: In production, this would use Azure AI Foundry's inference client
        to call the deployed model. This is a placeholder demonstrating the structure.
        """
        # Build the blog post structure
        blog_parts = [
            "# Life in the Backyard: An AI Adventure\n",
            f"\n## {message}\n" if message else "",
            f"\n{summary}\n" if summary else "",
            "\n## Today's Highlights\n",
        ]
        
        if events:
            blog_parts.append("\nOur backyard monitoring system captured some fascinating moments:\n")
            for i, event in enumerate(events[:5], 1):  # Limit to 5 events
                event_desc = event if isinstance(event, str) else event.get("description", "Unknown event")
                blog_parts.append(f"\n{i}. {event_desc}")
        else:
            blog_parts.append(
                "\nThe backyard was peaceful today, with our AI and IoT systems "
                "quietly monitoring and learning from the natural rhythms of the environment."
            )
        
        blog_parts.extend([
            "\n\n## What This Means\n",
            "\nThese observations help us understand the patterns in our backyard ecosystem. ",
            "Each data point tells a story, and our agents work together to make sense of it all, ",
            "turning raw telemetry into meaningful insights.\n",
            "\n---\n",
            "\n*Generated by BlogWriter Agent using Microsoft Agent Framework and Azure AI Foundry*\n"
        ])
        
        return "".join(blog_parts)
    
    def set_writing_style(self, style: str):
        """Set the writing style (e.g., 'entertaining', 'technical', 'casual')"""
        self.writing_style = style
        logger.info(f"[{self.name}] Writing style set to: {style}")
